# Generated by Django 5.0.6 on 2024-07-09 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('website_url', models.URLField(null=True)),
                ('linkedin_url', models.URLField(null=True)),
                ('subscription_type', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyIDSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NewsOfIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='NewsOfInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SubUserIDSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('linkedin_url', models.URLField(null=True)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=150)),
                ('user_type', models.CharField(default='admin', max_length=12)),
                ('company_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserIDSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('logo', models.ImageField(null=True, upload_to='clients_logo')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='app1.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excecutive_summary', models.TextField(null=True)),
                ('technology_profile', models.TextField(null=True)),
                ('sector', models.CharField(max_length=50)),
                ('no_of_employees', models.IntegerField(null=True)),
                ('business_introductory_video_file', models.FileField(null=True, upload_to='business_introductory')),
                ('business_introductory_video_url', models.URLField(null=True)),
                ('business_plan', models.FileField(null=True, upload_to='business_plan')),
                ('vision', models.TextField()),
                ('mission', models.TextField()),
                ('usp', models.TextField()),
                ('date_of_incorporation', models.DateField(null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('linkedin_url', models.URLField()),
                ('short_profile', models.TextField(null=True)),
                ('photo', models.ImageField(null=True, upload_to='photos')),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founders', to='app1.company')),
            ],
        ),
        migrations.CreateModel(
            name='HeterogenousProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('expected_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_growth_rate', models.IntegerField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
        migrations.CreateModel(
            name='HomogenousProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('selling_price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units_sold', models.IntegerField()),
                ('expected_growth_rate', models.IntegerField()),
                ('revenue_from_product', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
        migrations.CreateModel(
            name='ProfitLossBalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_recurring', models.FloatField()),
                ('revenue_one_time', models.FloatField()),
                ('other_income', models.FloatField()),
                ('total_income', models.FloatField()),
                ('cost_of_materials_consumed', models.FloatField()),
                ('changes_inventories_of_fg_wip', models.FloatField()),
                ('emp_benefits_expenses', models.FloatField()),
                ('depreciation_amortization_expenses', models.FloatField()),
                ('finance_cost', models.FloatField()),
                ('other_expenses', models.FloatField()),
                ('total_expenses', models.FloatField()),
                ('profit_before_tax', models.FloatField()),
                ('current_tax_expense', models.FloatField()),
                ('deferred_tax', models.FloatField()),
                ('profit_after_tax', models.FloatField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='app1.company')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('subuser_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('creator_id', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('linkedin_url', models.URLField(null=True)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=10)),
                ('user_type', models.CharField(max_length=12)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.user'),
        ),
    ]
