# Generated by Django 5.0.6 on 2024-06-29 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_team_creator_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitLossBalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_recurring', models.FloatField()),
                ('revenue_one_time', models.FloatField()),
                ('other_income', models.FloatField()),
                ('total_income', models.FloatField()),
                ('cost_of_materials_consumed', models.FloatField()),
                ('changes_inventories_of_fg_wip', models.FloatField()),
                ('emp_benefits_expenses', models.FloatField()),
                ('depreciation_amortization_expenses', models.FloatField()),
                ('finance_cost', models.FloatField()),
                ('other_expenses', models.FloatField()),
                ('total_expenses', models.FloatField()),
                ('profit_before_tax', models.FloatField()),
                ('current_tax_expense', models.FloatField()),
                ('deferred_tax', models.FloatField()),
                ('profit_after_tax', models.FloatField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
    ]
