# Generated by Django 5.0.6 on 2024-07-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_profitlossbalancesheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='date_of_incorporation',
            field=models.DateField(null=True),
        ),
    ]
