# Generated by Django 5.0.6 on 2024-07-02 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_companyprofile_date_of_incorporation'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeterogenousProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('expected_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_growth_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
        migrations.CreateModel(
            name='HomogenousProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('selling_price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units_sold', models.IntegerField()),
                ('expected_growth_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
    ]
