# Generated by Django 5.0.6 on 2024-07-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_heterogenousproduct_homogenousproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='homogenousproduct',
            name='revenue_from_product',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
