# Generated by Django 5.0.6 on 2024-07-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_homogenousproduct_revenue_from_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heterogenousproduct',
            name='expected_growth_rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='homogenousproduct',
            name='expected_growth_rate',
            field=models.IntegerField(),
        ),
    ]
